-- =====================================================================
-- PROJECT   :  ESTATEWISE REALTY ANALYTICS PROJECT
-- FILE      : business_insight_query
-- PURPOSE   : Answer real_Estate questions using SQL
--             (joins, aggregation, filtering, grouping, subqueries)
-- PREPARED BY: Anand bhujbal

USE estatewise_realty;

-- =====================================================================
-- SECTION A:   Beginner - SELECT, WHERE, ORDER BY, DISTINCT
-- =====================================================================

-- Q.1 List all properties located in 'Pune' with property_type = 'Apartment'. 

SELECT 
    property_id
FROM
    properties
WHERE
    property_type = 'Apartment'
        AND city = 'Pune';
        
    

-- Q.2 Display all bookings made through the 'Broker Referral' sales channel.

SELECT * FROM property_bookings
WHERE sales_channel = 'Broker Referral';

 
 -- Q.3 Find the distinct list of builders present in the properties table.

SELECT DISTINCT(builder) FROM properties;


-- Q.4 List all properties with base_price above Rs 1,50,00,000 (1.5 Cr), sorted by base_price descending.

SELECT * FROM properties
WHERE
    base_price > 15000000
ORDER BY base_price DESC; 

-- At property Table 45 properties  Are Greater than 1.50 cr Base Price

-- Q.5 Find all bookings where the discount given was more than 5%.

SELECT * FROM property_bookings
WHERE discount_pct > 5;
 
 -- 413 Properties are sold with >5 Discount_percentage
 
 -- Q.6 Display project_name, city and bhk for properties with an amenities_score of 9 or 10.
 
SELECT 
    project_name, city, bhk
FROM
    properties
WHERE
    amenities_score BETWEEN 9 AND 10;
    
    -- 26 Properties are sold with 9 Or 10 amenities_Score
    
    
--  Q.7 Count the total number of bookings recorded in the property_bookings table.

SELECT 
    COUNT(transaction_id) AS Total_Bookings
FROM
    property_bookings;
        
  -- Total_Bookings AS per Record is 2600    
  
-- =====================================================================
-- SECTION B :Intermediate - Aggregation, GROUP BY, HAVING, JOIN
-- =====================================================================
 
-- Q.8  Calculate the total sale value (sale_price) generated by each city.

SELECT 
    buyer_city, SUM(sale_price) AS Total_Sales
FROM
    property_bookings
GROUP BY buyer_city
ORDER BY Total_Sales DESC;

-- Q.9 Find the top 5 buyers by total amount spent across all their bookings.
SELECT 
    buyer_id,
    buyer_name,
    buyer_city,
    SUM(sale_price) AS Total_spent
FROM
    property_bookings
GROUP BY buyer_id , buyer_name , buyer_city
ORDER BY Total_spent DESC
LIMIT 5;

--  Q.10 Calculate the average discount percentage given per sales_channel.

SELECT 
    sales_channel,
    ROUND(AVG(discount_pct), 2) AS avg_discount_percentage
FROM
    property_bookings
GROUP BY sales_channel
ORDER BY avg_discount_percentage DESC;

-- Q.11 Find the number of bookings and total sale value handled by each agent. 

SELECT 
    agent_name,
    COUNT(transaction_id) AS number_of_Bookings,
    SUM(sale_price) AS Total_sales
FROM
    property_bookings
GROUP BY agent_name
ORDER BY Total_sales DESC;

-- Q.12 List all properties that have never been booked (zero bookings).

SELECT * FROM property_bookings
WHERE booking_date IS NULL;

-- Q.13 Calculate year-wise and month-wise total sale value across 2024 and 2025.
SELECT 
    YEAR(booking_date) AS Year_wise,
    MONTH(booking_date) AS month_wise,
    SUM(sale_price) AS Total_sales
FROM
    property_bookings
GROUP BY Year_wise , month_wise
ORDER BY Year_wise ASC;

-- Q.14 Find builders whose total sale value exceeds Rs 50 crore using GROUP BY with HAVING.

SELECT 
    builder, SUM(sale_price) AS Total_sale
FROM
    properties p
        INNER JOIN
    property_bookings b ON p.property_id = b.property_id
GROUP BY builder
HAVING Total_sale > 500000000;

-- Q.15 For each city, find the single highest-value booking (by sale_price).
SELECT 
    city, MAX(sale_price) AS highest_value
FROM
    properties p
        INNER JOIN
    property_bookings b ON p.property_id = b.property_id
GROUP BY city
ORDER BY highest_value DESC;

-- Q.16 Find the number of unique buyers who booked a property in each city.


SELECT 
    city, COUNT(DISTINCT (buyer_id)) AS unique_number_of_buyers
FROM
    properties p
        INNER JOIN
    property_bookings b ON p.property_id = b.property_id
GROUP BY city
ORDER BY unique_number_of_buyers DESC;

-- =====================================================================
-- SECTION c : Advanced - Subqueries, CTEs, Window Functions
-- =====================================================================

-- Q.17 Rank builders by total sale value generated, using a window function (RANK() or DENSE_RANK()).

SELECT 
 builder,
sum(sale_price)AS Total_sale_value, RANK()
OVER(ORDER BY  sum(sale_price) DESC) AS Rankins_of_builders FROM properties p
    INNER JOIN property_bookings b ON p.property_id = b.property_id
GROUP BY builder;
 
 -- Q.18 Using a CTE and ROW_NUMBER(), find the top-performing agent (by total sale value) in each city.
 
 WITH top_performer_by_city AS (SELECT agent_name,city,SUM(sale_price) AS total_sale FROM property_bookings b
INNER JOIN properties p ON p.property_id = b.property_id
GROUP BY agent_name,city),
ranking_agents AS (
SELECT agent_name,city,total_sale,ROW_NUMBER()OVER(PARTITION BY city ORDER BY total_sale DESC )
AS rrank_number FROM top_performer_by_city)
SELECT agent_name,city,total_sale FROM ranking_agents
WHERE rrank_number = 1;

-- Q.19 Calculate the running (cumulative) monthly sale value across 2024-2025 using a window function.

WITH monthly_sales AS
 (SELECT YEAR(booking_date) AS sale_year,MONTH(booking_date) AS sale_month,
 SUM(sale_price) monthly_total FROM properties p
INNER JOIN property_bookings b ON p.property_id = b.property_id
GROUP BY sale_year,sale_month
ORDER BY sale_year,sale_month)
SELECT sale_year,sale_month,monthly_total,SUM(monthly_total)OVER
(ORDER BY sale_year,sale_month)AS  running_total FROM monthly_sales
ORDER BY  sale_year,sale_month
;

-- Q.20 Identify buyers whose total spend is higher than the average spend across all buyers (subquery).

SELECT 
    property_id, 
    buyer_id, 
    buyer_name,
    buyer_city, 
    sale_price FROM property_bookings
WHERE
    sale_price > (SELECT 
            AVG(sale_price)
        FROM
            property_bookings);
		
-- Q.21 Calculate year-over-year (YoY) growth percentage in total sale value for each city using LAG()

WITH yearly_city_sales AS 
(SELECT city,YEAR(booking_date) AS sales_year,sum(sale_price) 
AS current_year_sales FROM properties p 
INNER JOIN property_bookings b ON p.property_id = b.property_id
GROUP BY city,YEAR(booking_date)),
sales_with_previous_year AS (
SELECT city,sales_year,current_year_sales,LAG(current_year_sales) 
OVER(PARTITION BY city ORDER BY sales_year)
AS previous_year_sales FROM yearly_city_sales)
SELECT city,sales_year,current_year_sales,previous_year_sales,
ROUND((current_year_sales - previous_year_sales)*100.00/( previous_year_sales),2)
 AS Growth_pct FROM sales_with_previous_year
ORDER BY city,sales_year;

-- Q.22 -- Segment buyers into 'Premium', 'Mid' and 'Budget' tiers based on total spend using CASE combined with aggregation, then count buyers per tier. 

with buyer_spent as (select buyer_name,sum(sale_price) as total_spent from properties p inner join property_bookings b on p.property_id = b.property_id
group by buyer_name),
category_count as (select 
  case when total_spent <=50000000 then "Budget"
 when total_spent between 100000000 and 200000000 then "Mid"
 when total_spent between  20000001 and 5000000000 then "Preimium" end as Price_category
 from buyer_spent)
select Price_category,count(Price_category) AS count_of_category from category_count
group by Price_category;

-- =====================================================================
-- SECTION D: REUSABLE VIEW FOR REPORTING / BI TOOLS
-- =====================================================================

-- Q18. Create a view that joins both tables into one clean, reusable
-- dataset - handy for quick reporting or connecting to Excel/Power BI


CREATE OR REPLACE VIEW Real_estate_summury AS
    SELECT 
        p.property_id,
        p.project_name,
        p.builder,
        p.city,
        p.locality,
        p.property_type,
        p.price_per_sqft,
        p.base_price,
        p.year_built,
        b.transaction_id,
        b.booking_date,
        b.buyer_id,
        b.buyer_name,
        b.sales_channel,
        b.discount_amount,
        b.sale_price,
        b.loan_amount,
        b.down_payment
    FROM
        properties p
            INNER JOIN
        property_bookings b ON p.property_id = b.property_id;